image: repo.htl-md.schule:5003/gradle:8.10.0-jdk21-alpine

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

deploy:
  stage: deploy
  script:
    - gradle publish
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    expire_in: 1 week
    name: "jar-files"
    paths:
      - build/libs/*.jar
  only:
    - main
    - test
    - dev
